author: Benjamin James Harrison-Sims
main: me.tehrainbowguy.XBank.XBank
name: XBank
startup: postworld
version: '1.7'
commands:
    xbank:
        description: Description
        usage: /<command> [arguments]
depend: [Vault]