author: Benjamin James Harrison-Sims
database: false
generator: http://dinnerbone.com/minecraft/tools/pluginator/
main: me.tehrainbowguy.XBank.XBank
name: XBank
startup: postworld
version: '1.2'
commands:
    xbank:
        description: Description
        usage: /<command> [arguments]
depend: [Vault]